
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.archivos.Jcup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BOOL = 53;
  public static final int REAL = 52;
  public static final int APPEND = 67;
  public static final int PACKED = 37;
  public static final int TYPE = 15;
  public static final int CONST = 14;
  public static final int TOSTRING = 73;
  public static final int DIFIGUAL = 32;
  public static final int POTENCIA = 18;
  public static final int DOBP = 9;
  public static final int DECRE = 45;
  public static final int STRUCT = 70;
  public static final int MAYORIGQ = 36;
  public static final int FALSE = 17;
  public static final int NOT = 42;
  public static final int IGUALIGUAL = 31;
  public static final int ARRAY = 56;
  public static final int MULTI = 5;
  public static final int VAR = 13;
  public static final int CIERRE = 12;
  public static final int RECORD = 38;
  public static final int PARC = 8;
  public static final int PARA = 7;
  public static final int MOD = 19;
  public static final int STARTWITH = 21;
  public static final int COMA = 11;
  public static final int ENTERO = 59;
  public static final int TRUE = 16;
  public static final int IGUAL = 10;
  public static final int WHILE = 26;
  public static final int LENGHT = 72;
  public static final int INCRE = 44;
  public static final int DECIMAL = 60;
  public static final int CHAR = 54;
  public static final int FIND = 74;
  public static final int IMPRIMIR = 55;
  public static final int DO = 28;
  public static final int FOR = 27;
  public static final int VOID = 20;
  public static final int DIV = 4;
  public static final int RETURN = 29;
  public static final int ELSE = 30;
  public static final int BREAK = 63;
  public static final int INT = 50;
  public static final int CORC = 49;
  public static final int CORA = 48;
  public static final int STRING_LITERAL = 58;
  public static final int EOF = 0;
  public static final int PUNTO = 68;
  public static final int DEFAULT = 22;
  public static final int SUMA = 2;
  public static final int SUBRANGO = 23;
  public static final int OR = 39;
  public static final int error = 1;
  public static final int RESTA = 3;
  public static final int MENORIGQ = 34;
  public static final int CONTINUE = 64;
  public static final int LIST = 66;
  public static final int IF = 25;
  public static final int ID = 62;
  public static final int MENORQ = 33;
  public static final int OF = 43;
  public static final int END = 57;
  public static final int UMENOS = 6;
  public static final int MAYORQ = 35;
  public static final int RANGO = 24;
  public static final int CHAR_LITERAL = 61;
  public static final int CADENA = 51;
  public static final int NEW = 65;
  public static final int ROUND = 71;
  public static final int AND = 40;
  public static final int LLAVEC = 47;
  public static final int LLAVEA = 46;
  public static final int REMOVE = 69;
  public static final int XOR = 41;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SUMA",
  "RESTA",
  "DIV",
  "MULTI",
  "UMENOS",
  "PARA",
  "PARC",
  "DOBP",
  "IGUAL",
  "COMA",
  "CIERRE",
  "VAR",
  "CONST",
  "TYPE",
  "TRUE",
  "FALSE",
  "POTENCIA",
  "MOD",
  "VOID",
  "STARTWITH",
  "DEFAULT",
  "SUBRANGO",
  "RANGO",
  "IF",
  "WHILE",
  "FOR",
  "DO",
  "RETURN",
  "ELSE",
  "IGUALIGUAL",
  "DIFIGUAL",
  "MENORQ",
  "MENORIGQ",
  "MAYORQ",
  "MAYORIGQ",
  "PACKED",
  "RECORD",
  "OR",
  "AND",
  "XOR",
  "NOT",
  "OF",
  "INCRE",
  "DECRE",
  "LLAVEA",
  "LLAVEC",
  "CORA",
  "CORC",
  "INT",
  "CADENA",
  "REAL",
  "BOOL",
  "CHAR",
  "IMPRIMIR",
  "ARRAY",
  "END",
  "STRING_LITERAL",
  "ENTERO",
  "DECIMAL",
  "CHAR_LITERAL",
  "ID",
  "BREAK",
  "CONTINUE",
  "NEW",
  "LIST",
  "APPEND",
  "PUNTO",
  "REMOVE",
  "STRUCT",
  "ROUND",
  "LENGHT",
  "TOSTRING",
  "FIND"
  };
}

